sudo: false
language: ruby
rvm:
  - 2.5.0
services:
  - postgresql
before_install: gem install bundler -v 1.16.1
before_script:
  - cd spec/demo && bundle install
  - psql -c 'create database jls_api_rails_demo_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
script:
  - bundle exec rake
  - cd spec/demo && bundle exec rake
