source 'https://rubygems.org'
ruby '2.5.0'

# Easy to use JLS:API server framework for Ruby on Rails backends.
gem 'jls_api_rails', path: '../..'

###
## Basics
###

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1'

# Use Puma as the app server
gem 'puma', '~> 3.7'

###
## Layout / Views
###

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# A Scope & Engine based, clean, powerful, customizable and sophisticated paginator
gem 'kaminari', '~> 1.1'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

###
## Browser-Scripting
###

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

###
## Model / Data
###

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

###
## Debugging
###

group :development, :test do
  # Call 'binding.pry' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug', platforms: [:mri, :mingw, :x64_mingw]

  # Loads environment variables from `.env`
  gem 'dotenv-rails'

  # More useful error page
  gem 'better_errors'

  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

###
## Dev Environment
###

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
end

###
## Code Quality
###

group :development, :test do
  # Retrieve the binding of a method's caller in MRI 1.9.2+
  gem 'binding_of_caller'
end

###
## Testing
###

group :test, :development do
  # Easily generate fake data such as names, addresses, and phone numbers
  gem 'faker'

  # Testing framework
  gem 'rspec-rails'

  # Strategies for cleaning databases
  gem 'database_cleaner'

  # a better fixtures replacement
  gem 'factory_bot_rails'

  # RSpec-compatible one-liners that test common Rails functionality
  gem 'shoulda-matchers'

  # Match JSON structures in expectations
  gem 'json_expressions'

  # Brings back `assigns` and `assert_template` to your Rails tests
  gem 'rails-controller-testing'

  # Preview mail in the browser instead of sending
  gem 'letter_opener'
end
